### ISSUE TITLE
Font Creation

### ISSUE THREAD

**Issue by schwos** [RafaelReyesCarmona/TinyTrackGPS#3]
Ran across your TinyTrackGPSPlus solution and liked how you saved memory by incorporating the logo, images into fonts. A couple of questions on your workflow to get there. 

Where did you get the LCDGFX font library you could import into a font editor specialist the GLCD font.
When you converted your logo into fonts you have any tips/lessons learned in taking that approach? They’re a tool you used to break it down  for you, or did you end up using Photoshop to split it up based upon pixel height and width..

Appreciate you sharing.

**Comment by RafaelReyesCarmona** [comment]
Hola, estoy encantado de que te guste mi solución. Pero he de decirte que la librería LCDGFX la utilicé en [TinyTrackGPS](https://github.com/RafaelReyesCarmona/TinyTrackGPS) que estaba desarrollado para ATmega328p al inicio y Lgt8f328p en las últimas versiones. TinyTrackGPSPlus utiliza la librería U8g2, de oliver (https://github.com/olikraus/u8g2). Toda la información sobre la librería LCDGFX la puedes encontrar en el github de lexus2k en [https://github.com/lexus2k/lcdgfx](https://github.com/lexus2k/lcdgfx). 

Para editar fuentes y hacer una fuente personalizada he seguido las instrucciones en la siguiente pagina: [https://github.com/lexus2k/lcdgfx/wiki/How-to-create-new-font-for-the-library](https://github.com/lexus2k/lcdgfx/wiki/How-to-create-new-font-for-the-library)

Puedo decirte que la estructura de un carácter es muy similar a un "tile" que usa la librería u8g2 en la función "drawtile". En este enlace tienes más información: https://github.com/olikraus/u8g2/wiki/u8x8reference#drawtile. La información de los píxeles se ordena en columnas de izquierda a derecha y de arriba hacia abajo. Con esta información puedes hacer pequeños cambios si no te queda bien el resultado. Muchos de los caracteres los programé con una calculadora binaria a hexadecimal.

Espero haberte ayudado. Si tienes alguna pregunta no dudes en ponerte en contacto conmigo. Un saludo.

--------------------------------------------------------------------------

Hi, I'm glad you like my solution. But I have to tell you that I used the LCDGFX library in [TinyTrackGPS](https://github.com/RafaelReyesCarmona/TinyTrackGPS) which was developed for ATmega328p at the beginning and Lgt8f328p in the last versions. TinyTrackGPSPlus uses the U8g2 library, by oliver ([https://github.com/olikraus/u8g2](https://github.com/olikraus/u8g2)). All information about the LCDGFX library can be found on the lexus2k github at [https://github.com/lexus2k/lcdgfx](https://github.com/lexus2k/lcdgfx).

To edit fonts and make a custom font, I followed the instructions on the following page: [https://github.com/lexus2k/lcdgfx/wiki/How-to-create-new-font-for-the-library](https://github.com/lexus2k/lcdgfx/wiki/How-to-create-new-font-for-the-library)

I can tell you that the structure of a character is very similar to a "tile" that the u8g2 library uses in the "drawtile" function. In this link you have more information: https://github.com/olikraus/u8g2/wiki/u8x8reference#drawtile. The pixel information is arranged in columns from left to right and from top to bottom. With this information you can make small changes if you don't like the result. I programmed many of the characters with a binary to hexadecimal calculator.

I hope I have helped you. If you have any questions, don't hesitate to contact me. Best regards.

**Comment by RafaelReyesCarmona** [comment]
Concretamente he modificado el codigo del archivo [canvas/fonts/fonts.c](https://github.com/lexus2k/lcdgfx/blob/master/src/canvas/fonts/fonts.c)  de la libreria LCDGFX para adaptarlo a mi proyecto. Código original:
--------------------------------------------------------------------
Specifically, I have modified the code of the canvas/fonts/fonts.c file of the LCDGFX library to adapt it to my project. Original code:

```
const PROGMEM uint8_t ssd1306xled_font8x16[] = {
    0x00, // 0x00 means fixed font type - the only supported by the library
    0x08, // 0x08 = 8 - font width in pixels
    0x10, // 0x10 = 16 - font height in pixels
    0x20, // Start char. (space)

    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, //   0
    0x00, 0x00, 0x00, 0xF8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x33, 0x30, 0x00, 0x00, 0x00, // ! 1
(...)
    0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00, 0x00, // | 92
    0x00, 0x02, 0x02, 0x7C, 0x80, 0x00, 0x00, 0x00, 0x00, 0x40, 0x40, 0x3F, 0x00, 0x00, 0x00, 0x00, // } 93
    0x00, 0x06, 0x01, 0x01, 0x02, 0x02, 0x04, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // ~ 94
};
```

**Comment by schwos** [comment]
Thank you for sharing, these steps I was aware of. More specifically what I was looking for was you modified one of the fonts provided within the LCDGFX library and removed characters and replaced a couple of standard characters with your logo and images. 

1.) Where did you get the font to load within one of the font editors, or did you just pick a true type/open type font that was same or close? 

2.) Your TingGPS logo uses; if I recall; 8 characters to make how did you break it down into the pixel count the font provided and the same question could be asked with respects to u8x8 drawtile which in reviewing the source it appears you opted to just post text only no logo.

BTW; you have a donation link? Appreciate the feedback and support as I squeeze our solution into the small memory of the Arduino; the ESP32 is easier.

thanks,

**Comment by RafaelReyesCarmona** [comment]
Entiendo lo que buscas. Es largo de explicar, pero intentaré hacerlo por pasos. Yo opté por una fuente de 8 pixeles de ancho por 16 de alto (ssd1306xled_font8x16) que puedes encontrar el código en [fonts.c](https://github.com/lexus2k/lcdgfx/blob/master/src/canvas/fonts/fonts.c). Cada línea es la representación de dos "tiles" de 8x8 píxeles, uno superior y otro inferior. En el caso del logo que es de 32x32 pixeles, utilizo dos líneas de 4 caracteres, en total 8 caracteres. Cada caracter es de 16 pixeles de alto, con lo que dos líneas son los 32 pixeles. De la misma manera, el ancho de un caracter es de 8 pixeles, con lo que 4 caracteres son los 32 pixeles de ancho. 
<img width="478" alt="image" src="https://github.com/RafaelReyesCarmona/TinyTrackGPSPlus/assets/78477791/70ad8a6d-e5ae-4bdb-8ac2-0e2c4add3c2f">

Cada carácter lo forman dos tiles de 8x8. Superior e inferior. El dibujo lo explica mejor:
<img width="255" alt="image" src="https://github.com/RafaelReyesCarmona/TinyTrackGPSPlus/assets/78477791/0c91d18b-2174-4e48-8a76-49c7eed84491">

En el código fuente se sustituye la línea del carácter ':' (por ejemplo) y cuando en el sketch se llame a la función para imprimir ':', se imprimirá el reloj de arena.
```
const PROGMEM uint8_t TinyTrackGPS_font8x16[] = {
    0x00, // 0x00 means fixed font type - the only supported by the library
    0x08, // 0x08 = 8 - font width in pixels
    0x10, // 0x10 = 16 - font height in pixels
    0x29, // Start char. (41)
    (...)
    // Chars for wait animation.
    /*up tile->*/0x01, 0x1f, 0x7f, 0xff, 0xff, 0x7f, 0x1f, 0x01, /*<- up , down-> */0x80, 0xf8, 0x86, 0x81, 0x81, 0x86, 0xf8, 0x80, /* <- down tile*/ // ':'->wait1 58
    (...)
};
```

El código original que imprime ':' es:
```
0x00, 0x00, 0x00, 0xC0, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x30, 0x00, 0x00, 0x00,
```

 Es importante saber el primer carácter de nuestra fuente personalizada. La línea siguiente será ese carácter. No se podrá imprimir un carácter anterior. Para el orden de caracteres se utiliza el código ASCII. Yo eliminé los caracteres que no necesitaba, empezando por el carácter 0x29 que es ")". Hice una reordenación de los caracteres haciendo que coincidieran el máximo de ellos con el orden ASCII. Los que no me interesaban los reprograme y en el código del programa hay que tener en cuenta que por ejemplo el espacio lo cambie por "?". Asi que si quiero imprimir un espacio tengo que pensar en imprimir "?". 

Para formar el logo hay que hacer el mismo proceso 8 veces. 4 caracteres de la línea superior y 4 de la inferior, fraccionando el dibujo. Así el logo se imprimirá con la instrucciones:
```
        this->print(6,1,"^_`a"); // first line
        this->print(6,2,"bcde"); // new line
```
^ - char 94
_ - char 95
` - char 96
a - char 97
b - char 98
c - char 99
d - char 100
e - char 101

He utilizado GIMP para convertir un dibujo en código, pero al final habitualmente tengo que retocar el resultado, fue una guía, pero no me dio un resultado como esperaba, así que como solo era un logo lo hice manualmente. Posiblemente con una hoja de excel o calc se pueda automatizar el proceso.

Espero haberte aclarado. Si te puedo ayudar en algo no dudes en preguntar. Un saludo.
---

**Comment by RafaelReyesCarmona** [comment]
You can donate at:

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/donate/?hosted_button_id=TSCH5FJDVYWP6)

Thanks.

**Comment by schwos** [comment]
This was very helpful.. but final clarification.. the translation may have not help me.. 

When you remove characters you didn’t want it would effect the character that comes up next correct? 

For example A, B, C, D if we remove B anytime we type Brown it will actually output C?

**Comment by RafaelReyesCarmona** [comment]
Es más complejo explicarlo que aplicarlo una vez que lo entiendes. Supongamos que solo necesitamos una fuente con números. Los codigos ASCII para los números son:
Hex code - char
0x30 - 0
0x31 - 1
0x32 - 2
0x33 - 3
(...) 
0x39 - 9

Al definir la fuente le decimos que el primer carácter es 0x30. La siguiente línea será el carácter 0. El último carácter definido es el 9. Si eliminamos la línea del carácter 1, cuando queramos imprimir 01234 se imprimirá 02345. El carácter 1 no se imprime, pero los caracteres se desplazan. Y cuando queramos imprimir 9, no se podrá porque estará desplazado. Pero si cambiamos el 1 por a. Ahora se imprimirá 0a234. Ahora el 9 si se imprime correctamente, solo hemos sustituido un carácter por otro. Si lo eliminamos todo se desplaza. 
-----

It is more complex to explain it than to apply it once you understand it. Suppose we only need a font with numbers. The ASCII codes for numbers are:
Hex code - char
0x30 - 0
0x31 - 1
0x32 - 2
0x33 - 3
(...)
0x39 - 9

When defining the font we tell it that the first character is 0x30. The next line will be character 0. The last character defined is 9. If we delete the line for character 1, when we want to print 01234 it will print 02345. The character 1 is not printed, but the characters are shifted. And when we want to print 9, it will not be printed because it will be shifted. But if we change the 1 to a. Now it will print 0a234. Now the 9 if it prints correctly, we have only replaced one character with another. If we delete it all, it will be shifted.
Traducido con DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by schwos** [comment]
Perfect you validated what I have been experiencing in my testing. Now I know I am not loosing my head in all this. Appreciate the validation and the guidance. It has been over 30 years since I wrote PCL fonts for the HP printers in my past career.
