### ISSUE TITLE
Adding nanoclass to Display

### ISSUE THREAD

**Issue by schwos** [RafaelReyesCarmona/TinyTrackGPS#4]
We are trying to determine how to add nanoengine to custom display control class in the approach you took with your TinyTrackGPS app.. We appreciate how TinyTrackGPS approached supporting multiple display/lcd libraries though we can also put our canvas routines within the object class to call together with all the nanoengine commands.

In a file display.h:
DisplaySSD1306_128x64_I2C* display;
typedef NanoEngine1<DisplaySSD1306_128x64_I2C> NanoEngineDemo;
NanoEngineDemo engine(display);

How can we approach this which will work and not irritate the compiler?

Thank You

**Comment by RafaelReyesCarmona** [comment]
Hi! En el fichero display.h he definido display como un puntero del tipo DisplaySSD1306_128x64_I2C. Para inicializar NanoEngine1 es necesario que el objeto esté creado. Esto sucede en el fichero display.cpp dentro de Display::start() línea 76
```
        display = new DisplaySSD1306_128x64_I2C(-1);
```

Para utilizar nanoengine añada la línea despues de ésta, quedando así:
![image](https://github.com/RafaelReyesCarmona/TinyTrackGPS/assets/78477791/ef889488-63aa-40aa-8a2e-2705b2aab738)
```
    #if defined(DISPLAY_TYPE_SDD1306_128X64_lcdgfx)
        display = new DisplaySSD1306_128x64_I2C(-1);
        NanoEngine1<DisplaySSD1306_128x64_I2C> engine(*display);

        display->begin();
        //display->setFixedFont(ssd1306xled_font8x16);
        //display->setFixedFont(ssd1306xled_font6x8);
        display->setFixedFont(TinyTrackGPS_font8x16);
    #endif
```
Observe que uso 'engine(*display)' ya que estoy usando punteros no objetos.

Despues no olvide las rutinas 'engine.drawCallback( )' y 'engine.begin()' para inicializar nanoengine. Así como las funciones 'engine.refresh()' y 'engine.display()' para dibujar la pantalla.

**Comment by schwos** [comment]
Appreciate the response but I attempted similar approaches and taking what you suggested the compiler complains; see compiler feedback on compile. 

> In file included from src/Display.cpp:26:0:
src/Display.h:58:13: error: 'display' does not name a type; did you mean 'Display'?
             display = new DisplaySSD1306_128x64_I2C(-1);
             ^~~~~~~
             Display
src/Display.h:59:53: error: expected ';' at end of member declaration
             NanoEngine1<DisplaySSD1306_128x64_I2C>* engine(*display);
                                                     ^~~~~~
src/Display.h:59:68: warning: ISO C++ forbids declaration of 'display' with no type [-fpermissive]
             NanoEngine1<DisplaySSD1306_128x64_I2C>* engine(*display);
                                                                    ^
src/Display.cpp: In member function 'void Display::start()':
src/Display.cpp:36:51: error: cannot convert 'DisplaySSD1306_128x64_I2C*' to 'int*' in assignment
         display = new DisplaySSD1306_128x64_I2C(-1);

Below is the beginning of the code for our Display.h file we like to build. Im missing something so simple but just can't get my head around what.. 


`class Display {
    private:
        //byte _offset;
        byte _width;       // Width pixels or numbers of columns for LCD.
        byte _height;       // Height pixels os numbers of rows for LCD.
        Display_Type _screen;
        #if defined(DISPLAY_TYPE_SDD1306_128X64_lcdgfx)
            //DisplaySSD1306_128x64_I2C* display;
            display = new DisplaySSD1306_128x64_I2C(-1);
            NanoEngine1<DisplaySSD1306_128x64_I2C> engine(*display);
        #endif
`

**Comment by RafaelReyesCarmona** [comment]
Try this:
In display.h this code:
![image](https://github.com/RafaelReyesCarmona/TinyTrackGPS/assets/78477791/e3eeb210-fffc-4b48-9099-c504c0537285)

And in display.cpp this code:
![image](https://github.com/RafaelReyesCarmona/TinyTrackGPS/assets/78477791/df5260cf-1414-43e3-927a-19b7fcaa871e)

Then compile right:
<img width="468" alt="image" src="https://github.com/RafaelReyesCarmona/TinyTrackGPS/assets/78477791/33107547-1077-4fca-b917-4bf0e7e22c59">

**Comment by schwos** [comment]
This compiles for me; thank you.. Now to move to engine calls vs display.. Thank you..

**Comment by RafaelReyesCarmona** [comment]
Other option more complex could be:
In display.h:
![image](https://github.com/RafaelReyesCarmona/TinyTrackGPS/assets/78477791/9940ace8-bed7-48dc-822d-5db4dc384f4e)

And in display.cpp:
![image](https://github.com/RafaelReyesCarmona/TinyTrackGPS/assets/78477791/52d3f119-5027-4ed0-a3d2-4e2c2f1365e6)

Always you must use engine.drawCallback( )' and 'engine.begin()' for initialize. And, 'engine.refresh()' and 'engine.display()' for draw screen. If use this new code change "." to "->". So 'engine.begin()' is now 'engine->begin()', and so.
